export OPENAI_LOGDIR=obayashi
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_040000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 40000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_060000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 60000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_080000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 80000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_090000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 90000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_110000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 110000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_120000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 120000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_130000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 130000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_140000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 140000
#mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_150000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 150000
mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_160000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 160000
mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_170000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 170000
mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_180000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 180000
mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_190000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 190000
mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_200000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 200000
mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_300000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 300000
mpiexec -n 1 python scripts/image_sample.py --image_size 256 --num_channels 128 --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 1000 --use_kl False --noise_schedule linear --rescale_learned_sigmas True --rescale_timesteps False --class_cond False --batch_size 4 --model_path output/obayashi/ema_0.9999_400000.pt --timestep_respacing 250 --use_ddim False --num_samples 8 --img_disp_nrow 4 --step_num 400000
